"""msg

Revision ID: 1d85540b1913
Revises: 
Create Date: 2025-07-11 09:35:43.051045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d85540b1913'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('steel_rate', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('oil_rate', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('rubber_rate', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('food_rate', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('gold_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'gold_rate')
    op.drop_column('cities', 'food_rate')
    op.drop_column('cities', 'rubber_rate')
    op.drop_column('cities', 'oil_rate')
    op.drop_column('cities', 'steel_rate')
    # ### end Alembic commands ###
