"""Created Unit Model

Revision ID: 4047da8e0508
Revises: 1d85540b1913
Create Date: 2025-07-13 05:53:13.030962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4047da8e0508'
down_revision: Union[str, Sequence[str], None] = '1d85540b1913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_type'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('construction_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('construction_finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('buildings_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('buildings_pkey'))
    )
    op.create_index(op.f('ix_buildings_type'), 'buildings', ['type'], unique=False)
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    # ### end Alembic commands ###
