"""Create building_types table

Revision ID: 820db5cd6de9
Revises: fe51821a9135
Create Date: 2025-07-21 10:04:53.636927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '820db5cd6de9'
down_revision: Union[str, Sequence[str], None] = 'fe51821a9135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_types')
    op.drop_table('unit_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_training',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('training_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('training_finishes_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('unit_training_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('unit_training_pkey'))
    )
    op.create_table('unit_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_training_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('base_attack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_defense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_cost', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('base_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('base_carry_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_life', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('population_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upkeep_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unlock_requirements', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_building', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_research', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('special_ability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unit_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('unit_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
