"""Add grid coordinates for building and building queue models

Revision ID: e704c83c4529
Revises: 4b44b4c249c5
Create Date: 2025-07-25 08:34:38.233966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e704c83c4529'
down_revision: Union[str, Sequence[str], None] = '4b44b4c249c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_queues', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('building_queues', sa.Column('y', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'y')
    op.drop_column('buildings', 'x')
    op.drop_column('building_queues', 'y')
    op.drop_column('building_queues', 'x')
    # ### end Alembic commands ###
